package com.dbopt.app.service;

import com.dbopt.app.entity.Department;
import com.dbopt.app.entity.Employee;
import com.dbopt.app.repository.DepartmentRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.dao.DataAccessResourceFailureException;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {@link DepartmentService}.
 *
 * WHAT IS A UNIT TEST?
 * A unit test exercises the smallest testable piece of code (here, one method
 * of one class) in complete isolation from its real collaborators (database,
 * network, file system, other services). "Isolation" is the key word: we
 * never want a Spring context, a real database connection, or a real
 * repository implementation involved. We replace DepartmentRepository with a
 * Mockito mock so the test is fast (milliseconds, not seconds), deterministic
 * (no flaky DB state), and tells us precisely whether DepartmentService's own
 * logic is correct.
 *
 * WHY IT MATTERS
 * - Fast feedback: hundreds of unit tests run in seconds, so they can run on
 *   every save/commit.
 * - Regression safety net: if someone changes getDepartmentEmployeeCountsNPlusOne()
 *   and breaks the LinkedHashMap ordering or the employee count logic, these
 *   tests fail immediately instead of a tester finding it days later.
 * - Documentation: a well-named test method tells the next developer exactly
 *   what behavior is guaranteed.
 *
 * TEST PYRAMID
 * Picture a pyramid with three layers:
 *   - Top (few, slow, expensive): End-to-end / UI tests.
 *   - Middle (some): Integration tests — real Spring context, real (or
 *     in-memory) database, e.g. @SpringBootTest or @DataJpaTest hitting an
 *     H2 database to prove the JPQL in DepartmentRepository actually fetches
 *     rows correctly.
 *   - Bottom (many, fast, cheap): Unit tests — exactly what this class
 *     contains. They should be the majority of your test suite because they
 *     are cheapest to write and run.
 * This file lives at the BOTTOM of the pyramid: DepartmentRepository is
 * mocked, so we are testing DepartmentService's logic only, not real SQL.
 */
@ExtendWith(MockitoExtension.class) // (1) Activates Mockito for this class: initializes
// every field annotated with @Mock, wires @InjectMocks, and validates stubs after each
// test. Without this extension, @Mock/@InjectMocks fields would stay null.
@DisplayName("DepartmentService unit tests")
class DepartmentServiceTest {

    @Mock // (2) Creates a fake (dynamically generated) DepartmentRepository.
    // It implements the JpaRepository interface but every method returns
    // null / does nothing until we explicitly program it with when(...).
    // This is how we isolate DepartmentService from the real database.
    private DepartmentRepository departmentRepository;

    @InjectMocks // (3) Creates a real DepartmentService instance and injects the
    // @Mock above into its constructor (DepartmentService has one constructor
    // generated by Lombok's @RequiredArgsConstructor: DepartmentService(DepartmentRepository)).
    // Mockito picks the constructor automatically and passes the mock in.
    private DepartmentService departmentService;

    // Shared test fixtures rebuilt before every test so tests cannot leak
    // state into one another.
    private Department engineering;
    private Department sales;

    @BeforeEach // (4) Runs before EVERY @Test method in this class. Used to set up
    // fresh "Arrange" data so each test starts from a known, identical state.
    // If we built `engineering`/`sales` once as static fields instead, one
    // test could mutate them and silently break a later test.
    void setUp() {
        Employee alice = new Employee(1L, "Alice", "alice@corp.com", "Pune", null, null);
        Employee bob = new Employee(2L, "Bob", "bob@corp.com", "Pune", null, null);
        Employee carol = new Employee(3L, "Carol", "carol@corp.com", "Mumbai", null, null);

        engineering = new Department(1L, "Engineering", List.of(alice, bob));
        sales = new Department(2L, "Sales", List.of(carol));
    }

    @Test
    @DisplayName("getDepartmentEmployeeCountsNPlusOne() maps each department to its employee count")
    void getDepartmentEmployeeCountsNPlusOne_returnsCountsPerDepartment() {
        // ===== ARRANGE =====
        // "Given a known set of departments returned by the repository..."
        // when(...).thenReturn(...) is Mockito's stubbing API: it tells the
        // mock "the NEXT time findAllPlain() is called, return this list"
        // instead of running real JPA/SQL code.
        when(departmentRepository.findAllPlain())
                .thenReturn(List.of(engineering, sales));

        // ===== ACT =====
        // "When we call the method under test..."
        // This is the ONE line that actually exercises DepartmentService's logic.
        Map<String, Integer> result = departmentService.getDepartmentEmployeeCountsNPlusOne();

        // ===== ASSERT =====
        // "Then the result should look like this."
        // assertThat(...) is AssertJ's fluent assertion API (bundled with
        // spring-boot-starter-test). containsEntry checks both the key and
        // value, so we know the counting logic (d.getEmployees().size()) is
        // correct, not just that the map has 2 keys.
        assertThat(result)
                .hasSize(2)
                .containsEntry("Engineering", 2)
                .containsEntry("Sales", 1);

        // verify(mock, times(1)).method() proves DepartmentService called
        // findAllPlain() exactly once — not zero times (logic bug: data
        // never fetched) and not twice (logic bug: wasteful duplicate query,
        // which is exactly the kind of inefficiency this project cares about).
        verify(departmentRepository, times(1)).findAllPlain();

        // Negative verification: this method must NOT have touched the
        // fetch-join query path. Mixing up the two repository methods would
        // be a realistic copy/paste bug this test guards against.
        verify(departmentRepository, never()).findAllWithEmployees();
    }

    @Test
    @DisplayName("getDepartmentEmployeeCountsFetchJoin() maps each department to its employee count")
    void getDepartmentEmployeeCountsFetchJoin_returnsCountsPerDepartment() {
        // ARRANGE — stub the OTHER repository method this time.
        when(departmentRepository.findAllWithEmployees())
                .thenReturn(List.of(engineering, sales));

        // ACT
        Map<String, Integer> result = departmentService.getDepartmentEmployeeCountsFetchJoin();

        // ASSERT
        assertThat(result)
                .hasSize(2)
                .containsEntry("Engineering", 2)
                .containsEntry("Sales", 1);

        verify(departmentRepository, times(1)).findAllWithEmployees();
        verify(departmentRepository, never()).findAllPlain();
    }

    @Test
    @DisplayName("getDepartmentEmployeeCountsNPlusOne() returns an empty map when there are no departments")
    void getDepartmentEmployeeCountsNPlusOne_noDepartments_returnsEmptyMap() {
        // ARRANGE — an empty list is a real edge case: a brand-new database
        // with no departments seeded yet.
        when(departmentRepository.findAllPlain()).thenReturn(List.of());

        // ACT
        Map<String, Integer> result = departmentService.getDepartmentEmployeeCountsNPlusOne();

        // ASSERT
        assertThat(result).isEmpty();
        verify(departmentRepository, times(1)).findAllPlain();
    }

    @Test
    @DisplayName("getDepartmentEmployeeCountsNPlusOne() treats a department with no employees as count 0")
    void getDepartmentEmployeeCountsNPlusOne_departmentWithNoEmployees_countsZero() {
        // ARRANGE — Department.employees is an empty list, not null, because
        // the @OneToMany collection is always populated by Hibernate (even if
        // empty) once persisted; this mirrors that real shape.
        Department empty = new Department(3L, "Legal", List.of());
        when(departmentRepository.findAllPlain()).thenReturn(List.of(empty));

        // ACT
        Map<String, Integer> result = departmentService.getDepartmentEmployeeCountsNPlusOne();

        // ASSERT
        assertThat(result).containsEntry("Legal", 0);
    }

    @Test
    @DisplayName("getDepartmentEmployeeCountsNPlusOne() propagates the exception when the repository fails")
    void getDepartmentEmployeeCountsNPlusOne_repositoryThrows_exceptionPropagates() {
        // EXCEPTION TESTING
        // ARRANGE — instead of thenReturn(...), use thenThrow(...) to make
        // the mock simulate a real-world failure: the database connection
        // pool is exhausted, or the DB is unreachable. Spring Data wraps such
        // failures in subclasses of DataAccessException.
        when(departmentRepository.findAllPlain())
                .thenThrow(new DataAccessResourceFailureException("DB connection pool exhausted"));

        // ACT + ASSERT combined.
        // assertThrows(ExpectedType.class, executable) runs the lambda and
        // fails the test if the exception is NOT thrown, or if a different
        // exception type is thrown. It returns the caught exception so we
        // can assert on its message too.
        DataAccessResourceFailureException ex = assertThrows(
                DataAccessResourceFailureException.class,
                () -> departmentService.getDepartmentEmployeeCountsNPlusOne()
        );

        assertThat(ex.getMessage()).contains("DB connection pool exhausted");
        verify(departmentRepository, times(1)).findAllPlain();
    }
}